name: Compile DTS to DTB

on: 
  workflow_dispatch

# permissions:
#   contents: write

env:
  APT: sudo apt -y -qq -o=Dpkg::Use-Pty=0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install prerequisites
      run: |
        $APT update
        $APT install autoconf build-essential bc bison flex device-tree-compiler
    
    - name: Set up environment
      run: |
        cd /tmp/
        git clone --depth=1 "https://github.com/CoreELEC/linux-amlogic.git" -o linux-amlogic
        ls -al ./linux-amlogic
        du -sh ./linux-amlogic
       
        cd ./linux-amlogic
        git clone --depth=1 "https://github.com/maaaaz/coreelec_common_drivers.git" -o coreelec_common_drivers
        ls -al ./coreelec_common_drivers
        du -sh ./linux-amlogic
    
